from fpdf import FPDF
from services.budget import format_currency
import re


class TripPDF(FPDF):
    """Custom PDF class for travel itinerary."""

    def __init__(self, destination: str):
        super().__init__()
        self.destination = destination
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f"AI Travel Planner  |  {self.destination} Trip", align="L")
        self.ln(2)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by AI Travel Planner  |  Page {self.page_no()}", align="C")


def _clean_text(text: str) -> str:
    """Remove markdown symbols and clean text for PDF."""
    # Remove markdown bold/italic
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    # Remove markdown headers
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)
    # Remove emoji (FPDF doesn't support unicode emoji well)
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002700-\U000027BF"
        "\U0001F900-\U0001F9FF"
        "\U00002600-\U000026FF"
        "]+",
        flags=re.UNICODE
    )
    text = emoji_pattern.sub("", text)
    text = text.strip()
    return text


def _section_title(pdf: FPDF, title: str):
    """Render a section title."""
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(37, 99, 235)  # Blue
    pdf.set_fill_color(239, 246, 255)
    pdf.cell(0, 8, _clean_text(title), fill=True, ln=True)
    pdf.ln(2)
    pdf.set_text_color(0, 0, 0)


def _body_text(pdf: FPDF, text: str, indent: int = 0):
    """Render body text with optional indent."""
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.set_x(10 + indent)
    pdf.multi_cell(190 - indent, 6, _clean_text(text))


def _render_trip_header(pdf: FPDF, state: dict):
    """Render the trip summary header page."""
    currency = state.get("current_currency", "INR")
    total    = state.get("total_budget", 0)
    persons  = state.get("persons", 1)
    per_p    = state.get("per_person_budget") or (int(total / persons) if persons > 0 else total)

    # Big title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 12, _clean_text(state.get("destination", "Trip")), ln=True, align="C")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, "AI-Generated Travel Itinerary", ln=True, align="C")
    pdf.ln(6)

    # Divider
    pdf.set_draw_color(37, 99, 235)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(6)

    # Trip details grid
    details = [
        ("Duration",    f"{state.get('days', '-')} days"),
        ("Total Budget", format_currency(total, currency)),
        ("Per Person",  format_currency(per_p, currency)),
        ("Travellers",  f"{persons} ({state.get('group_type', 'solo').capitalize()})"),
        ("Vibe",        (state.get("mood") or "chill").capitalize()),
        ("Weather",     state.get("weather_desc", "Not specified")),
    ]
    if state.get("travel_month"):
        details.append(("Travel Month", state["travel_month"]))
    if state.get("travel_season"):
        details.append(("Season", state["travel_season"]))

    pdf.set_font("Helvetica", "", 11)
    for label, value in details:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(55, 8, f"{label}:", ln=False)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, _clean_text(str(value)), ln=True)

    pdf.ln(4)
    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)


def _render_itinerary(pdf: FPDF, itinerary: str):
    """Parse and render the itinerary section."""
    _section_title(pdf, "Your Itinerary")

    lines = itinerary.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(2)
            continue

        clean = _clean_text(line)
        if not clean:
            continue

        # Day headers (### Day 1: ...)
        if re.match(r"^(###?\s*)?Day\s+\d+", line, re.IGNORECASE):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(37, 99, 235)
            pdf.set_fill_color(239, 246, 255)
            pdf.cell(0, 8, clean, fill=True, ln=True)
            pdf.set_text_color(0, 0, 0)

        # Sub-sections (Morning / Afternoon / Evening)
        elif any(t in line for t in ["Morning:", "Afternoon:", "Evening:", "Morning", "Afternoon", "Evening"]):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(60, 60, 60)
            pdf.set_x(14)
            pdf.multi_cell(186, 6, clean)
            pdf.set_text_color(0, 0, 0)

        # Section headers (Local Tips, Must Try Food)
        elif re.match(r"^(Local Tips|Must Try|Tips|Food)", clean, re.IGNORECASE):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 7, clean, ln=True)
            pdf.set_text_color(0, 0, 0)

        # Bullet points
        elif line.startswith("-") or line.startswith("*") or line.startswith("•"):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.set_x(16)
            pdf.multi_cell(184, 6, f"• {clean.lstrip('-').lstrip('*').lstrip('•').strip()}")

        # Normal text
        else:
            _body_text(pdf, clean)

    pdf.ln(4)


def _render_budget(pdf: FPDF, budget: dict, currency: str, total: float):
    """Render budget breakdown as a table."""
    _section_title(pdf, "Budget Breakdown")

    categories = [
        ("Accommodation", budget.get("accommodation", 0)),
        ("Food",          budget.get("food", 0)),
        ("Transport",     budget.get("transport", 0)),
        ("Activities",    budget.get("activities", 0)),
        ("Miscellaneous", budget.get("miscellaneous", 0)),
    ]

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(100, 8, "Category", border=0, fill=True)
    pdf.cell(50,  8, "Amount", border=0, fill=True)
    pdf.cell(40,  8, "% of Total", border=0, fill=True, ln=True)

    # Table rows
    pdf.set_font("Helvetica", "", 10)
    fill = False
    for label, amount in categories:
        pdf.set_fill_color(239, 246, 255) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(30, 30, 30)
        pct = f"{(amount / total * 100):.1f}%" if total > 0 else "0%"
        pdf.cell(100, 7, label, border=0, fill=True)
        pdf.cell(50,  7, format_currency(amount, currency), border=0, fill=True)
        pdf.cell(40,  7, pct, border=0, fill=True, ln=True)
        fill = not fill

    # Total row
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(220, 230, 255)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(100, 8, "TOTAL", border=0, fill=True)
    pdf.cell(50,  8, format_currency(total, currency), border=0, fill=True)
    pdf.cell(40,  8, "100%", border=0, fill=True, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Budget tips
    tips = budget.get("tips", [])
    if tips:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 7, "Budget Tips:", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        for tip in tips:
            pdf.set_x(14)
            pdf.multi_cell(186, 6, f"• {_clean_text(tip)}")

    pdf.ln(4)


def _render_packing_list(pdf: FPDF, packing: dict):
    """Render categorized packing list."""
    _section_title(pdf, "Packing List")

    category_labels = {
        "clothing":   "Clothing",
        "toiletries": "Toiletries",
        "documents":  "Documents",
        "gadgets":    "Gadgets & Electronics",
        "medical":    "Medical & Health",
        "misc":       "Miscellaneous",
    }

    for key, label in category_labels.items():
        items = packing.get(key, [])
        if not items:
            continue

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(0, 7, label, ln=True)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)

        # 2-column layout for packing items
        col_width = 90
        for i in range(0, len(items), 2):
            left  = f"• {_clean_text(items[i])}"
            right = f"• {_clean_text(items[i+1])}" if i+1 < len(items) else ""
            pdf.set_x(14)
            pdf.cell(col_width, 6, left)
            pdf.cell(col_width, 6, right, ln=True)

        pdf.ln(2)

    pdf.ln(4)


def generate_pdf(state: dict) -> bytes:
    """
    Master function — generates full trip PDF.
    Takes streamlit session state dict.
    Returns PDF as bytes for Streamlit download button.
    """
    destination = state.get("destination", "Trip")
    currency    = state.get("current_currency", "INR")
    total       = state.get("total_budget", 0)
    itinerary   = state.get("current_itinerary", "")
    budget      = state.get("current_budget", {})
    packing     = state.get("packing_list")

    pdf = TripPDF(destination=destination)
    pdf.add_page()

    # 1. Trip header
    _render_trip_header(pdf, state)

    # 2. Itinerary
    if itinerary:
        _render_itinerary(pdf, itinerary)

    # 3. Budget breakdown
    if budget:
        pdf.add_page()
        _render_budget(pdf, budget, currency, total)

    # 4. Packing list (if generated)
    if packing:
        _render_packing_list(pdf, packing)

    return bytes(pdf.output())